import { useCallback, useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useAuth } from "../hooks/useAuth.js";
import { supabase } from "../supabase/client.js";
import * as service from "../services/notificationService.js";
import NotificationDetailHeader from "../sections/notification/NotificationDetailHeader.jsx";
import NotificationIcon from "../components/notification/NotificationIcon.jsx";
import NotificationTime from "../components/notification/NotificationTime.jsx";
import NotificationTracking from "../sections/notification/NotificationTracking.jsx";
import NotificationInfo from "../sections/notification/NotificationInfo.jsx";
import NotificationFooter from "../sections/notification/NotificationFooter.jsx";

export default function NotificationDetail(){const {notificationId}=useParams();const {user}=useAuth();const navigate=useNavigate();const [notification,setNotification]=useState(null);const [order,setOrder]=useState(null);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!user)return;const item=await service.getNotification(notificationId,user.id);setNotification(item);if(item){if(!item.is_read)await service.markAsRead(item.id,user.id);setOrder(await service.getOrderForNotification(item.order_id,user.id));}setLoading(false);},[notificationId,user]);useEffect(()=>{load();if(!user)return undefined;const channel=supabase.channel(`notification-detail-${notificationId}`).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`id=eq.${notificationId}`},load).subscribe();return()=>{supabase.removeChannel(channel)};},[load,notificationId,user]);const remove=async()=>{if(!notification||!window.confirm('Hapus notifikasi ini?'))return;await service.deleteNotification(notification.id,user.id);navigate('/notifikasi',{replace:true});};if(loading)return <div className="grid min-h-dvh place-items-center bg-white"><Loader2 className="animate-spin text-primary"/></div>;if(!notification)return <div className="grid min-h-dvh place-items-center bg-white text-sm text-gray-500">Notifikasi tidak ditemukan.</div>;const trackable=notification.order_id&&['driver_assigned','driver_on_the_way','driver_arrived','order_delivered','order'].includes(notification.type);return <div className="mx-auto min-h-dvh max-w-3xl bg-white pb-6"><NotificationDetailHeader onBack={()=>navigate(-1)} onDelete={remove}/><main className="space-y-3 p-3"><section className="rounded-3xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><NotificationIcon type={notification.type}/><div><h1 className="text-base font-extrabold">{notification.title}</h1><div className="mt-1"><NotificationTime value={notification.created_at}/></div></div></div><p className="mt-4 text-xs leading-6 text-gray-600">{notification.message}</p></section>{trackable&&<NotificationTracking metadata={notification.metadata} order={order}/>} {notification.order_id&&<NotificationInfo notification={notification} order={order}/>}<NotificationFooter notification={notification} order={order} onTrack={()=>order&&navigate(`/lacak-pesanan/${order.id}`)}/></main></div>;}
