import { useCallback, useEffect, useState } from "react";
import { Building2, Check, Info, Loader2, Plus, ShieldCheck, Smartphone, WalletCards, X } from "lucide-react";
import ProfilePageHeader from "../components/profile/ProfilePageHeader.jsx";
import { useAuth } from "../hooks/useAuth.js";
import { addPaymentMethod, listPaymentMethods } from "../services/paymentMethodService.js";
import { supabase } from "../supabase/client.js";

const EMPTY={type:"bank",provider:"",custom_provider:"",account_name:"",account_number:"",label:"",is_primary:false};
const OTHER="__other";
const PROVIDER_GROUPS={
  bank:[
    {label:"Bank Nasional",items:["BCA","BRI","BNI","Mandiri","BTN","Bank Syariah Indonesia (BSI)","Bank Mega","Bank Bukopin","Bank Sinarmas"]},
    {label:"Bank Swasta & Digital",items:["CIMB Niaga","Danamon","PermataBank","OCBC Indonesia","PaninBank","Maybank Indonesia","Bank Jago","SeaBank","Bank Neo Commerce","Allo Bank","blu by BCA Digital","Bank Raya","Hibank","Superbank","LINE Bank","Krom Bank","Amar Bank","Bank Aladin Syariah","Bank Muamalat"]},
    {label:"Bank Pembangunan Daerah",items:["Bank Aceh Syariah","Bank Sumut","Bank Nagari","Bank Riau Kepri Syariah","Bank Jambi","Bank Bengkulu","Bank Sumsel Babel","Bank Lampung","Bank BJB","Bank DKI","Bank Jateng","Bank BPD DIY","Bank Jatim","Bank Kalbar","Bank Kalteng","Bank Kalsel","Bank Kaltimtara","Bank Sulselbar","Bank SulutGo","Bank Sulteng","Bank Sultra","Bank BTPN","Bank NTB Syariah","Bank NTT","Bank Maluku Malut","Bank Papua","Bank Bali"]},
    {label:"Bank Internasional",items:["HSBC Indonesia","Standard Chartered Indonesia","DBS Indonesia","UOB Indonesia","Bank of China Indonesia","Citibank Indonesia","J Trust Bank","KEB Hana Bank","Bank Woori Saudara","Bank ICBC Indonesia","MUFG Bank Indonesia"]},
    {label:"Lainnya",items:[OTHER]},
  ],
  ewallet:[
    {label:"Dompet Digital",items:["DANA","GoPay","OVO","ShopeePay","LinkAja","i.saku","Sakuku","JakOne Pay","MotionPay","AstraPay","KasPro","Doku Wallet"]},
    {label:"Uang Elektronik & Akun Digital",items:["BRIZZI","TapCash BNI","Mandiri e-money","Flazz BCA","Finpay Money","Paytren"]},
    {label:"Lainnya",items:[OTHER]},
  ],
};
const THEMES={BCA:"from-[#07549b] to-[#06396f]",BRI:"from-[#0877bd] to-[#07549c]",BNI:"from-[#008b82] to-[#006b69]",Mandiri:"from-[#00529c] to-[#003b70]",BTN:"from-[#075c9f] to-[#063b70]","Bank Syariah Indonesia (BSI)":"from-[#00a88e] to-[#087b67]","CIMB Niaga":"from-[#b6001d] to-[#78000e]",Danamon:"from-[#f5a800] to-[#e36d00]",PermataBank:"from-[#238f5a] to-[#12633b]","Bank Jago":"from-[#f36f32] to-[#8a388f]",SeaBank:"from-[#f26032] to-[#e7451e]",DANA:"from-[#1595e7] to-[#0879c9]",GoPay:"from-[#00a9d4] to-[#008f72]",OVO:"from-[#654098] to-[#442574]",ShopeePay:"from-[#ee4d2d] to-[#cf3218]",LinkAja:"from-[#dd1731] to-[#a90016]"};
const formatNumber=value=>String(value||"").replace(/\D/g,"").replace(/(.{4})/g,"$1 ").trim();

function PaymentCard({row}){const Icon=row.type==="bank"?Building2:Smartphone;const theme=THEMES[row.provider]||"from-slate-700 to-slate-950";const status={verified:"Terverifikasi",rejected:"Ditolak",pending:"Menunggu verifikasi"}[row.status]||"Menunggu verifikasi";return <article className={`relative isolate min-h-56 overflow-hidden rounded-3xl bg-gradient-to-br ${theme} p-5 text-white shadow-[0_16px_35px_rgba(15,23,42,.18)]`}>
  <span className="absolute -right-14 -top-14 -z-10 h-40 w-40 rounded-full border-[24px] border-white/10"/><span className="absolute -bottom-16 -left-8 -z-10 h-36 w-36 rounded-full bg-black/10"/>
  <div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/20 bg-white/15 backdrop-blur"><Icon size={19}/></span><div className="min-w-0"><h2 className="truncate text-base font-black">{row.provider}</h2><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-white/65">{row.type==="bank"?"Rekening Bank":"Dompet Digital"}</p></div></div>{row.is_primary&&<span className="rounded-full border border-white/20 bg-white/15 px-2.5 py-1 text-[8px] font-bold uppercase tracking-wide">Utama</span>}</div>
  <div className="mt-7"><p className="text-[8px] font-semibold uppercase tracking-[.18em] text-white/55">Nomor {row.type==="bank"?"Rekening":"E-Wallet"}</p><p className="mt-1.5 break-all font-mono text-lg font-bold tracking-[.08em]">{formatNumber(row.account_number)}</p></div>
  <div className="mt-6 flex items-end justify-between gap-3"><div className="min-w-0"><p className="text-[8px] font-semibold uppercase tracking-[.16em] text-white/55">Nama Pemilik</p><p className="mt-1 truncate text-xs font-bold uppercase">{row.account_name}</p></div><p className="max-w-[40%] truncate rounded-lg bg-black/10 px-2 py-1 text-[9px] font-semibold">{row.label||(row.type==="bank"?"Pribadi":"E-Wallet")}</p></div>
  <div className="mt-4 flex items-center justify-between border-t border-white/15 pt-3 text-[8px] font-semibold text-white/65"><span>{status}</span><span>Ditambahkan {new Date(row.created_at).toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"})}</span></div>
</article>}

export default function PaymentMethods(){const{user}=useAuth();const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[form,setForm]=useState(EMPTY);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[filter,setFilter]=useState("all");
const load=useCallback(async()=>{if(!user)return;try{setRows(await listPaymentMethods(user.id));setError("");}catch(reason){setError(reason.message)}finally{setLoading(false)}},[user]);
useEffect(()=>{load();if(!user)return;const channel=supabase.channel(`payment-methods-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"user_payment_methods",filter:`user_id=eq.${user.id}`},load).subscribe();return()=>supabase.removeChannel(channel)},[load,user]);
const showAdd=()=>{setForm({...EMPTY,is_primary:rows.length===0});setError("");setNotice("");setOpen(true)};
const submit=async event=>{event.preventDefault();setError("");const provider=form.provider===OTHER?form.custom_provider.trim():form.provider;if(provider.length<2){setError("Masukkan nama bank atau layanan lainnya minimal 2 karakter.");return;}setSaving(true);try{await addPaymentMethod(user.id,{...form,provider});setNotice("Metode pembayaran berhasil ditambahkan.");setOpen(false);await load()}catch(reason){setError(reason.message||"Metode pembayaran belum dapat ditambahkan.")}finally{setSaving(false)}};
const visibleRows=filter==="all"?rows:rows.filter(row=>row.type===filter);const bankCount=rows.filter(row=>row.type==="bank").length;const walletCount=rows.filter(row=>row.type==="ewallet").length;
return <div className="space-y-4"><ProfilePageHeader title="Metode Pembayaran" action={<button onClick={showAdd} className="grid h-10 w-10 place-items-center rounded-full bg-primary text-white shadow-lg shadow-orange-200" aria-label="Tambah metode pembayaran"><Plus size={18}/></button>}/>
  <section className="overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-sm"><div className="bg-gradient-to-br from-slate-900 to-slate-700 p-5 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/55">Dompet Pembayaran</p><h2 className="mt-1 text-lg font-black">{rows.length} metode tersimpan</h2><p className="mt-1 text-[10px] text-white/60">Semua rekening Anda, rapi dalam satu tempat.</p></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white/10"><WalletCards size={21}/></span></div><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/10 p-3"><strong className="text-lg">{bankCount}</strong><p className="text-[9px] text-white/55">Rekening bank</p></div><div className="rounded-2xl bg-white/10 p-3"><strong className="text-lg">{walletCount}</strong><p className="text-[9px] text-white/55">E-Wallet</p></div></div></div><div className="flex gap-3 p-4"><ShieldCheck size={17} className="shrink-0 text-emerald-600"/><div><p className="text-[11px] font-bold text-gray-800">Data pembayaran terlindungi</p><p className="mt-0.5 text-[9px] leading-4 text-gray-500">Anda bisa menambah rekening baru. Untuk mengubah atau menghapus data, hubungi admin.</p></div></div></section>
  {error&&<p role="alert" className="rounded-2xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}{notice&&<p className="rounded-2xl bg-emerald-50 p-3 text-xs text-emerald-700">{notice}</p>}
  {!loading&&rows.length>0&&<nav className="grid grid-cols-3 rounded-2xl bg-gray-100 p-1" aria-label="Filter metode pembayaran">{[["all","Semua",rows.length],["bank","Bank",bankCount],["ewallet","E-Wallet",walletCount]].map(([value,label,count])=><button key={value} onClick={()=>setFilter(value)} className={`min-h-10 rounded-xl text-[10px] font-bold transition ${filter===value?"bg-white text-primary shadow-sm":"text-gray-500"}`}>{label} <span className="ml-1 opacity-60">{count}</span></button>)}</nav>}
  {loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:rows.length?<><section className="grid gap-4 sm:grid-cols-2">{visibleRows.map(row=><PaymentCard key={row.id} row={row}/>)}</section>{visibleRows.length===0&&<p className="rounded-2xl border border-dashed bg-white p-8 text-center text-xs text-gray-400">Belum ada metode dalam kategori ini.</p>}<button onClick={showAdd} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-primary/20 bg-primary-50 text-xs font-extrabold text-primary"><Plus size={17}/>Tambah Rekening Lainnya</button></>:<section className="rounded-3xl border border-dashed border-gray-200 bg-white p-10 text-center"><WalletCards className="mx-auto text-gray-300" size={38}/><h2 className="mt-4 text-sm font-extrabold">Belum ada metode pembayaran</h2><p className="mt-1 text-xs text-gray-400">Tambahkan rekening bank atau dompet digital pertama Anda.</p><button onClick={showAdd} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-5 text-xs font-bold text-white"><Plus size={16}/>Tambah Metode</button></section>}
  {open&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/50 sm:place-items-center sm:p-4"><form onSubmit={submit} className="max-h-[94dvh] w-full max-w-md overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wide text-primary">Tambah Baru</p><h2 className="mt-1 text-lg font-black">Metode Pembayaran</h2></div><button type="button" onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-gray-100"><X size={17}/></button></div>
  {error&&<p role="alert" className="mt-4 rounded-xl border border-red-100 bg-red-50 p-3 text-[10px] font-semibold leading-4 text-red-700">{error}</p>}
  <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-3"><p className="flex gap-2 text-[10px] font-bold text-blue-800"><Info size={15} className="shrink-0"/>Nama pemilik wajib sama persis dengan nama yang terdaftar pada rekening atau dompet digital.</p><p className="mt-2 text-[9px] text-blue-700/70">Contoh: jika nama pada rekening adalah “Rons Saputra”, masukkan <strong>Rons Saputra</strong>, bukan nama panggilan.</p></div>
  <div className="mt-4 grid grid-cols-2 gap-2">{[["bank","Rekening Bank",Building2],["ewallet","E-Wallet",Smartphone]].map(([value,label,Icon])=><button key={value} type="button" onClick={()=>setForm({...form,type:value,provider:"",custom_provider:""})} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl border text-xs font-bold ${form.type===value?"border-primary bg-primary-50 text-primary":"border-gray-200"}`}><Icon size={16}/>{label}</button>)}</div>
  <div className="mt-4 space-y-3"><label className="block text-[10px] font-bold text-gray-500">{form.type==="bank"?"Bank penerbit":"Penyedia e-wallet"} *<select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value,custom_provider:""})} required className="mt-1 h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-xs"><option value="">Pilih bank atau provider</option>{PROVIDER_GROUPS[form.type].map(group=><optgroup key={group.label} label={group.label}>{group.items.map(item=><option key={item} value={item}>{item===OTHER?"Bank / layanan lainnya":item}</option>)}</optgroup>)}</select></label>{form.provider===OTHER&&<label className="block text-[10px] font-bold text-gray-500">Nama bank / layanan *<input required minLength={2} maxLength={60} placeholder="Masukkan nama bank atau layanan" value={form.custom_provider} onChange={e=>setForm({...form,custom_provider:e.target.value})} className="mt-1 h-11 w-full rounded-xl border border-gray-200 px-3 text-xs outline-none focus:border-primary"/></label>}<label className="block text-[10px] font-bold text-gray-500">Nama pemilik rekening *<input required minLength={3} maxLength={100} placeholder="Contoh: Rons Saputra" value={form.account_name} onChange={e=>setForm({...form,account_name:e.target.value})} className="mt-1 h-11 w-full rounded-xl border border-gray-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="block text-[10px] font-bold text-gray-500">Nomor rekening / dompet digital *<input required type="tel" inputMode="numeric" pattern="[0-9 ]{6,34}" placeholder="Contoh: 1234567890" value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value.replace(/[^0-9 ]/g,"")})} className="mt-1 h-11 w-full rounded-xl border border-gray-200 px-3 font-mono text-xs outline-none focus:border-primary"/></label><label className="block text-[10px] font-bold text-gray-500">Label rekening (opsional)<input maxLength={50} placeholder="Contoh: Rekening Utama" value={form.label} onChange={e=>setForm({...form,label:e.target.value})} className="mt-1 h-11 w-full rounded-xl border border-gray-200 px-3 text-xs outline-none focus:border-primary"/></label><label className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 text-xs font-semibold"><input type="checkbox" checked={form.is_primary} onChange={e=>setForm({...form,is_primary:e.target.checked})} className="h-4 w-4 accent-orange-600"/>Jadikan metode utama</label></div>
  <p className="mt-4 rounded-xl bg-amber-50 p-3 text-[9px] leading-4 text-amber-800">Periksa kembali data sebelum menyimpan. Perubahan dan penghapusan hanya dapat dilakukan oleh administrator.</p><button disabled={saving} className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary text-xs font-bold text-white disabled:opacity-50">{saving?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>}Simpan Metode</button></form></div>}
</div>}
