import { ArrowLeft, ChevronDown, CircleHelp, Clock3, ExternalLink, HeartHandshake, Info, Mail, MessageCircle, ShieldCheck, Sparkles, Target } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";

const faqItems = [
  ["Bagaimana cara membuat pesanan?", "Pilih produk, tentukan varian dan jumlah, lalu tambahkan ke keranjang. Periksa alamat dan metode pembayaran sebelum menyelesaikan checkout."],
  ["Bagaimana melacak pesanan?", "Buka menu Pesanan Saya, pilih pesanan aktif, kemudian tekan Lacak Pesanan untuk melihat status terbaru."],
  ["Berapa lama waktu pengiriman?", "Estimasi umumnya 30–60 menit, tergantung lokasi, antrean pesanan, kondisi perjalanan, dan layanan pengiriman yang dipilih."],
  ["Apakah bisa memesan tanpa akun?", "Bisa. Pilih produk lalu gunakan pilihan Pesan via WhatsApp. Riwayat pesanan dan keranjang tersimpan tersedia setelah masuk ke akun."],
  ["Apakah tersedia produk frozen?", "Ketersediaan varian frozen dapat dilihat pada detail produk. Pilihan yang habis atau dinonaktifkan tidak dapat dipesan."],
  ["Bagaimana mengubah alamat?", "Buka Alamat Saya pada halaman profil, kemudian tambah atau pilih alamat utama yang akan digunakan."],
  ["Bagaimana menggunakan poin atau reward?", "Buka Poin Saya atau Reward pada halaman profil. Penukaran mengikuti saldo, masa berlaku, dan ketentuan reward."],
  ["Apa yang harus dilakukan jika akun digunakan orang lain?", "Segera ubah kata sandi, keluar dari perangkat yang tidak dikenali, dan hubungi layanan pelanggan resmi."],
];

const privacySections = [
  ["Informasi yang dikumpulkan", "Nama, kontak, alamat, lokasi yang diizinkan, informasi akun, keranjang, wishlist, riwayat pesanan, transaksi, metode pembayaran yang dipilih, serta data perangkat yang diperlukan untuk keamanan layanan."],
  ["Penggunaan informasi", "Data digunakan untuk menjalankan pemesanan dan pengiriman, menyampaikan status, menyediakan layanan pelanggan, menjaga keamanan, mencegah penyalahgunaan, dan meningkatkan kualitas sistem."],
  ["Lokasi perangkat", "Akses lokasi hanya dilakukan setelah pengguna memberi izin dan digunakan untuk membantu menentukan alamat atau menjalankan fitur pemesanan terkait."],
  ["Pembayaran", "Pembayaran tertentu dapat diproses oleh penyedia pihak ketiga. Dimsum Lumer tidak menyimpan PIN, OTP, CVV, atau informasi rahasia pembayaran yang tidak diperlukan."],
  ["Penyimpanan dan keamanan", "Kami menerapkan langkah keamanan yang wajar. Pengguna tetap bertanggung jawab menjaga kata sandi, perangkat, dan kerahasiaan kode verifikasi."],
  ["Pembagian informasi", "Data pribadi tidak dijual. Informasi hanya diberikan secara terbatas kepada penyedia pembayaran, pengiriman, infrastruktur teknologi, atau pihak yang diperlukan untuk menjalankan layanan dan kewajiban hukum."],
  ["Hak pengguna", "Pengguna dapat meminta pembaruan, perbaikan, atau penghapusan data sesuai ketentuan dan kemampuan layanan. Data tertentu dapat tetap disimpan untuk transaksi, keamanan, pencatatan usaha, atau kewajiban hukum."],
  ["Layanan pihak ketiga", "Database, autentikasi, peta, pembayaran, pengiriman, analitik, dan komunikasi dapat tunduk pada kebijakan privasi masing-masing penyedia."],
  ["Perubahan kebijakan", "Kebijakan dapat diperbarui mengikuti perubahan fitur, teknologi, proses bisnis, atau ketentuan hukum."],
];

const values = [
  ["Kualitas", "Memperhatikan produk dari persiapan hingga penyajian."],
  ["Kebersihan", "Menjaga area, alat, kemasan, dan proses penanganan."],
  ["Konsistensi", "Berupaya memberikan pengalaman yang seragam."],
  ["Kepedulian", "Memperhatikan detail kecil yang dirasakan pelanggan."],
  ["Kepercayaan", "Menghindari klaim yang belum dapat dibuktikan."],
];

function PageShell({ title, subtitle, icon: Icon, children }) {
  const navigate = useNavigate();
  return <div className="mx-auto min-h-dvh w-full max-w-2xl bg-gray-50 pb-24">
    <header className="flex min-h-16 items-center border-b border-gray-100 bg-white px-3"><button onClick={()=>navigate(-1)} aria-label="Kembali" className="grid h-10 w-10 place-items-center rounded-full hover:bg-gray-100"><ArrowLeft size={20}/></button><div className="min-w-0 flex-1 px-2 text-center"><h1 className="truncate text-sm font-extrabold">{title}</h1><p className="mt-0.5 truncate text-[10px] text-gray-500">{subtitle}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary-50 text-primary"><Icon size={19}/></span></header>
    <main className="space-y-3 p-3">{children}</main>
  </div>;
}

function HelpPage(){const number=(import.meta.env.VITE_ADMIN_WA_NUMBER||'').replace(/\D/g,'');const whatsapp=number?`https://wa.me/${number}?text=${encodeURIComponent('Halo Admin Dimsum Lumer, saya membutuhkan bantuan.')}`:null;return <PageShell title="Bantuan" subtitle="Kami siap membantu" icon={CircleHelp}><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-primary-700 via-primary to-orange-400 p-6 text-white shadow-lg"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><MessageCircle/></span><h2 className="mt-5 text-xl font-extrabold">Ada yang bisa kami bantu?</h2><p className="mt-2 text-xs leading-6 text-white/85">Sampaikan pertanyaan atau kendala pesanan melalui layanan pelanggan resmi Dimsum Lumer.</p>{whatsapp?<a href={whatsapp} target="_blank" rel="noreferrer" className="mt-5 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#25D366] text-sm font-bold text-white"><MessageCircle size={18}/>Hubungi melalui WhatsApp<ExternalLink size={14}/></a>:<p className="mt-5 rounded-xl bg-white/15 p-3 text-xs">Nomor layanan pelanggan belum dikonfigurasi.</p>}</section><section className="grid gap-3 sm:grid-cols-2"><article className="rounded-3xl bg-white p-5 shadow-sm"><Clock3 className="text-primary"/><h3 className="mt-3 text-sm font-bold">Sebelum menghubungi</h3><p className="mt-2 text-xs leading-5 text-gray-500">Siapkan nomor pesanan dan penjelasan singkat agar bantuan dapat diberikan lebih cepat.</p></article><article className="rounded-3xl bg-white p-5 shadow-sm"><ShieldCheck className="text-primary"/><h3 className="mt-3 text-sm font-bold">Tetap aman</h3><p className="mt-2 text-xs leading-5 text-gray-500">Kami tidak pernah meminta kata sandi, PIN, OTP, atau CVV melalui pesan pribadi.</p></article></section></PageShell>}

function FaqPage(){return <PageShell title="FAQ" subtitle="Pertanyaan yang sering diajukan" icon={CircleHelp}><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-base font-extrabold">Temukan jawaban dengan cepat</h2><p className="mt-1 text-xs leading-5 text-gray-500">Buka pertanyaan untuk melihat penjelasan.</p></section><section className="space-y-2">{faqItems.map(([question,answer])=><details key={question} className="group rounded-2xl border border-gray-100 bg-white shadow-sm"><summary className="flex min-h-14 cursor-pointer list-none items-center gap-3 px-4 py-3 text-xs font-bold"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary">?</span><span className="flex-1">{question}</span><ChevronDown size={17} className="text-gray-400 transition-transform group-open:rotate-180"/></summary><p className="border-t border-gray-50 px-4 py-4 text-xs leading-6 text-gray-600">{answer}</p></details>)}</section></PageShell>}

function PrivacyPage(){return <PageShell title="Kebijakan Privasi" subtitle="Perlindungan dan penggunaan data" icon={ShieldCheck}><section className="rounded-3xl bg-[#171717] p-6 text-white shadow-lg"><ShieldCheck className="text-amber-300" size={30}/><h2 className="mt-4 text-xl font-extrabold">Privasi pelanggan adalah tanggung jawab kami.</h2><p className="mt-2 text-xs leading-6 text-gray-300">Terakhir diperbarui: 10 Agustus 2026</p></section><section className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs leading-6 text-gray-600">Kebijakan ini menjelaskan bagaimana Dimsum Lumer mengumpulkan, menggunakan, menyimpan, dan melindungi informasi pengguna. Dengan menggunakan layanan, pengguna dianggap telah membaca dan memahami kebijakan ini.</p></section><section className="space-y-2">{privacySections.map(([title,body],index)=><article key={title} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-primary-50 text-xs font-extrabold text-primary">{index+1}</span><div><h2 className="text-xs font-extrabold">{title}</h2><p className="mt-2 text-xs leading-6 text-gray-600">{body}</p></div></div></article>)}</section><section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-sm font-extrabold text-amber-900">Hubungi kami</h2><p className="mt-2 text-xs leading-5 text-amber-800">Pertanyaan, permintaan, atau keluhan mengenai data pribadi dapat disampaikan melalui menu Bantuan.</p></section></PageShell>}

function AboutPage(){return <PageShell title="Tentang Kami" subtitle="Cerita, visi, misi, dan nilai kami" icon={Info}><section className="rounded-3xl bg-[#171717] p-6 text-white shadow-lg"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-300">Dimsum Lumer</p><h2 className="mt-3 text-2xl font-extrabold">Gurih di Luar, Lumer di Dalam!</h2><p className="mt-3 text-xs leading-6 text-gray-300">Kami menghadirkan dimsum yang nikmat sekaligus pengalaman produk yang rapi, praktis, dan terasa premium sejak pesanan diterima.</p></section><section className="rounded-3xl bg-white p-5 shadow-sm"><Sparkles className="text-primary"/><h2 className="mt-3 text-base font-extrabold">Cerita kami</h2><p className="mt-2 text-xs leading-6 text-gray-600">Dimsum Lumer dikembangkan dengan perhatian pada rasa, kebersihan proses, kerapian penyajian, kemasan, dan pelayanan. Kami percaya produk yang baik lahir dari perhatian pada hal-hal kecil.</p></section><section className="grid gap-3 sm:grid-cols-2"><article className="rounded-3xl bg-white p-5 shadow-sm"><Target className="text-primary"/><h2 className="mt-3 text-base font-extrabold">Visi</h2><p className="mt-2 text-xs leading-6 text-gray-600">Menjadi brand dimsum yang dipercaya karena rasa, kualitas penyajian, identitas yang hangat, dan pengalaman pelanggan.</p></article><article className="rounded-3xl bg-white p-5 shadow-sm"><HeartHandshake className="text-primary"/><h2 className="mt-3 text-base font-extrabold">Misi</h2><ul className="mt-2 list-disc space-y-2 pl-4 text-xs leading-5 text-gray-600"><li>Menjaga kualitas dan rasa.</li><li>Menangani makanan secara bersih.</li><li>Memberikan pelayanan yang ramah.</li><li>Terus memperbaiki pengalaman pelanggan.</li></ul></article></section><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-base font-extrabold">Nilai Dimsum Lumer</h2><div className="mt-4 grid gap-2">{values.map(([title,body])=><div key={title} className="rounded-2xl bg-gray-50 p-4"><h3 className="text-xs font-extrabold text-primary">{title}</h3><p className="mt-1 text-xs leading-5 text-gray-600">{body}</p></div>)}</div></section></PageShell>}

export default function ProfileInformation(){const {section}=useParams();if(section==='bantuan')return <HelpPage/>;if(section==='faq')return <FaqPage/>;if(section==='privasi')return <PrivacyPage/>;if(section==='tentang')return <AboutPage/>;return <PageShell title="Informasi" subtitle="Halaman tidak ditemukan" icon={Info}><section className="rounded-3xl bg-white p-6 text-center shadow-sm"><Mail className="mx-auto text-gray-400"/><p className="mt-3 text-sm font-bold">Informasi tidak ditemukan.</p></section></PageShell>}
