import { useEffect,useRef,useState } from "react";
import { CheckCircle2,Eye,EyeOff,KeyRound,Loader2,Mail,RotateCw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../supabase/client.js";
import { requestPasswordReset,updatePassword,verifyPasswordRecoveryOtp } from "../services/authService.js";

const passwordValid=(value)=>value.length>=8&&/[A-Za-z]/.test(value)&&/[0-9]/.test(value);

export default function ResetPassword(){
  const navigate=useNavigate();const otpRefs=useRef([]);const [step,setStep]=useState('email');const [email,setEmail]=useState('');const [otp,setOtp]=useState(Array(6).fill(''));const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [countdown,setCountdown]=useState(0);

  useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data})=>{if(mounted&&data.session&&window.location.hash)setStep('password');});const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(mounted&&event==='PASSWORD_RECOVERY')setStep('password');});return()=>{mounted=false;subscription.unsubscribe();};},[]);
  useEffect(()=>{if(countdown<=0)return undefined;const timer=window.setInterval(()=>setCountdown((value)=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[countdown]);

  const send=async(event)=>{event?.preventDefault();setError('');setMessage('');if(!/^\S+@\S+\.\S+$/.test(email.trim())){setError('Masukkan alamat email yang valid.');return;}setLoading(true);try{await requestPasswordReset(email.trim().toLowerCase());setStep('otp');setCountdown(60);setMessage('Kode pemulihan telah dikirim. Periksa Kotak Masuk dan folder Spam.');}catch(err){setError(err.message||'Email pemulihan belum dapat dikirim.');}finally{setLoading(false);}};
  const updateOtp=(index,value)=>{const digit=value.replace(/\D/g,'').slice(-1);setOtp((current)=>current.map((item,itemIndex)=>itemIndex===index?digit:item));if(digit&&index<5)otpRefs.current[index+1]?.focus();};
  const otpKey=(index,event)=>{if(event.key==='Backspace'&&!otp[index]&&index>0)otpRefs.current[index-1]?.focus();};
  const verify=async(event)=>{event.preventDefault();const token=otp.join('');setError('');if(token.length!==6){setError('Masukkan 6 digit kode OTP.');return;}setLoading(true);try{await verifyPasswordRecoveryOtp(email,token);setStep('password');setMessage('Kode benar. Silakan buat kata sandi baru.');}catch(err){setError(/expired|invalid/i.test(err.message||'')?'Kode OTP salah atau sudah kedaluwarsa.':err.message);}finally{setLoading(false);}};
  const save=async(event)=>{event.preventDefault();setError('');if(!passwordValid(password)){setError('Kata sandi minimal 8 karakter dan berisi huruf serta angka.');return;}if(password!==confirm){setError('Konfirmasi kata sandi tidak sama.');return;}setLoading(true);try{await updatePassword(password);await supabase.auth.signOut();navigate('/login',{replace:true,state:{passwordUpdated:true}});}catch(err){setError(err.message||'Kata sandi belum dapat diperbarui.');}finally{setLoading(false);}};

  return <div className="mx-auto w-full max-w-md bg-white px-1 pb-2"><main className="mx-auto max-w-sm"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-orange-50 text-primary"><KeyRound size={25}/></span><h1 className="mt-4 text-center text-xl font-extrabold text-gray-950">Lupa Kata Sandi</h1><p className="mx-auto mt-1 max-w-xs text-center text-[10px] leading-5 text-gray-500">{step==='email'?'Masukkan email akun Dimsum Lumer untuk menerima kode pemulihan.':step==='otp'?`Masukkan 6 digit kode yang dikirim ke ${email}.`:'Buat kata sandi baru untuk akun kamu.'}</p>{message&&<div className="mt-5 flex gap-2 rounded-2xl border border-emerald-100 bg-emerald-50 p-3 text-[9px] leading-4 text-emerald-700"><CheckCircle2 size={15} className="shrink-0"/>{message}</div>}{error&&<div className="mt-5 rounded-2xl border border-red-100 bg-red-50 p-3 text-center text-[9px] leading-4 text-red-600">{error}</div>}
    {step==='email'&&<form onSubmit={send} className="mt-6 space-y-4"><label className="flex h-12 items-center gap-3 rounded-2xl border border-gray-200 bg-gray-50 px-4 focus-within:border-primary focus-within:bg-white"><Mail size={17} className="text-gray-400"/><input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} autoComplete="email" placeholder="nama@email.com" className="min-w-0 flex-1 bg-transparent text-xs outline-none" required/></label><Submit loading={loading}>Kirim Kode OTP</Submit></form>}
    {step==='otp'&&<form onSubmit={verify} className="mt-6"><div className="grid grid-cols-6 gap-2">{otp.map((digit,index)=><input key={index} ref={(node)=>otpRefs.current[index]=node} value={digit} onChange={(event)=>updateOtp(index,event.target.value)} onKeyDown={(event)=>otpKey(index,event)} onPaste={index===0?(event)=>{event.preventDefault();const digits=event.clipboardData.getData('text').replace(/\D/g,'').slice(0,6).split('');setOtp(Array.from({length:6},(_,i)=>digits[i]||''));otpRefs.current[Math.min(digits.length,5)]?.focus();}:undefined} inputMode="numeric" autoComplete={index===0?'one-time-code':'off'} maxLength={1} aria-label={`Digit OTP ${index+1}`} className="h-12 min-w-0 rounded-xl border border-gray-200 bg-gray-50 text-center text-base font-extrabold outline-none focus:border-primary focus:bg-white"/> )}</div><div className="mt-5"><Submit loading={loading}>Verifikasi OTP</Submit></div><button type="button" disabled={countdown>0||loading} onClick={send} className="mt-4 flex w-full items-center justify-center gap-1.5 text-[9px] font-bold text-primary disabled:text-gray-400"><RotateCw size={12}/>{countdown>0?`Kirim ulang dalam ${countdown} detik`:'Kirim Ulang Kode'}</button><button type="button" onClick={()=>setStep('email')} className="mt-3 w-full text-center text-[9px] text-gray-500">Ganti alamat email</button></form>}
    {step==='password'&&<form onSubmit={save} className="mt-6 space-y-3"><Password value={password} onChange={setPassword} show={show} toggle={()=>setShow(!show)} label="Kata sandi baru"/><Password value={confirm} onChange={setConfirm} show={show} label="Ulangi kata sandi baru"/><p className="px-1 text-[8px] leading-4 text-gray-400">Minimal 8 karakter, mengandung huruf dan angka.</p><Submit loading={loading}>Simpan Kata Sandi</Submit></form>}
  </main></div>;
}

function Submit({loading,children}){return <button disabled={loading} className="flex h-12 w-full items-center justify-center rounded-2xl bg-primary text-xs font-bold text-white shadow-lg shadow-primary/20 disabled:opacity-60">{loading?<Loader2 size={17} className="animate-spin"/>:children}</button>}
function Password({value,onChange,show,toggle,label}){return <label className="flex h-12 items-center gap-3 rounded-2xl border border-gray-200 bg-gray-50 px-4 focus-within:border-primary focus-within:bg-white"><KeyRound size={16} className="text-gray-400"/><input type={show?'text':'password'} value={value} onChange={(event)=>onChange(event.target.value)} autoComplete="new-password" placeholder={label} className="min-w-0 flex-1 bg-transparent text-xs outline-none" required/>{toggle&&<button type="button" onClick={toggle} aria-label="Tampilkan kata sandi">{show?<EyeOff size={16}/>:<Eye size={16}/>}</button>}</label>}
