import { useEffect, useState } from "react";
import { CheckCircle2, Eye, EyeOff, KeyRound, Loader2 } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "../supabase/client.js";

const validPassword=(value)=>value.length>=8&&/[A-Za-z]/.test(value)&&/[0-9]/.test(value);

export default function ResetPassword(){
  const navigate=useNavigate();const [status,setStatus]=useState('checking');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{let active=true;const ready=()=>{if(active){setStatus('ready');setError('');}};const fail=(message)=>{if(active){setStatus('invalid');setError(message);}};const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')ready();});const initialize=async()=>{try{const url=new URL(window.location.href);const authError=url.searchParams.get('error_description');if(authError)throw new Error(decodeURIComponent(authError.replace(/\+/g,' ')));const code=url.searchParams.get('code');const hash=new URLSearchParams(url.hash.replace(/^#/,''));const accessToken=hash.get('access_token');const refreshToken=hash.get('refresh_token');if(code){const {error:exchangeError}=await supabase.auth.exchangeCodeForSession(code);if(exchangeError)throw exchangeError;window.history.replaceState({},document.title,'/reset-password');ready();return;}if(accessToken&&refreshToken){const {error:sessionError}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(sessionError)throw sessionError;window.history.replaceState({},document.title,'/reset-password');ready();return;}const {data,error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;const recoveryHint=hash.get('type')==='recovery'||url.searchParams.get('type')==='recovery';if(data.session&&recoveryHint){ready();return;}window.setTimeout(()=>{if(active)setStatus((current)=>current==='checking'?'invalid':current);},1200);}catch(reason){fail(reason.message||'Tautan pemulihan tidak valid atau sudah kedaluwarsa.');}};initialize();return()=>{active=false;subscription.unsubscribe();};},[]);
  const save=async(event)=>{event.preventDefault();setError('');if(!validPassword(password)){setError('Kata sandi minimal 8 karakter dan harus berisi huruf serta angka.');return;}if(password!==confirm){setError('Konfirmasi kata sandi tidak sama.');return;}setSaving(true);try{const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;setStatus('success');await supabase.auth.signOut();window.setTimeout(()=>navigate('/login',{replace:true,state:{passwordUpdated:true}}),1200);}catch(reason){setError(reason.message||'Kata sandi gagal diperbarui. Minta tautan baru dan coba lagi.');}finally{setSaving(false);}};
  if(status==='checking')return <div className="grid min-h-56 place-items-center text-center"><div><Loader2 className="mx-auto animate-spin text-primary"/><p className="mt-3 text-xs text-gray-500">Memverifikasi tautan pemulihan…</p></div></div>;
  if(status==='invalid')return <div className="mx-auto max-w-sm text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-red-50 text-red-500"><KeyRound size={27}/></span><h1 className="mt-4 text-xl font-extrabold">Tautan tidak valid</h1><p className="mt-2 text-xs leading-5 text-gray-500">{error||'Tautan sudah digunakan atau kedaluwarsa.'}</p><Link to="/forgot-password" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-primary px-5 text-xs font-bold text-white">Kirim tautan baru</Link></div>;
  if(status==='success')return <div className="mx-auto max-w-sm text-center"><CheckCircle2 size={54} className="mx-auto text-emerald-600"/><h1 className="mt-4 text-xl font-bold">Kata sandi diperbarui</h1><p className="mt-2 text-xs text-slate-500">Anda akan diarahkan ke halaman masuk…</p></div>;
  return <div className="mx-auto w-full max-w-sm text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-orange-50 text-primary"><KeyRound size={27}/></span><h1 className="mt-4 text-xl font-extrabold">Buat Kata Sandi Baru</h1><p className="mt-1 text-xs leading-5 text-gray-500">Gunakan kata sandi yang kuat dan belum pernah digunakan.</p><form onSubmit={save} className="mt-6 space-y-3 text-left">{[['password',password,setPassword,'Kata sandi baru'],['confirm',confirm,setConfirm,'Ulangi kata sandi']].map(([name,value,setValue,label])=><label key={name} className="flex min-h-12 items-center gap-3 rounded-2xl border border-gray-200 bg-gray-50 px-4 focus-within:border-primary"><KeyRound size={16} className="text-gray-400"/><input required type={show?'text':'password'} autoComplete="new-password" value={value} onChange={(event)=>setValue(event.target.value)} placeholder={label} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/>{name==='password'&&<button type="button" onClick={()=>setShow((value)=>!value)} aria-label="Tampilkan kata sandi">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</label>)}<p className="px-1 text-[10px] leading-5 text-gray-500">Minimal 8 karakter, mengandung huruf dan angka.</p>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-center text-xs text-red-600">{error}</p>}<button disabled={saving} className="flex min-h-12 w-full items-center justify-center rounded-2xl bg-primary text-sm font-bold text-white disabled:opacity-60">{saving?<Loader2 size={17} className="animate-spin"/>:'Simpan Kata Sandi Baru'}</button></form></div>;
}
