import { useState } from 'react';
import { Edit2, ImagePlus, Loader2, Plus, Trash2, X } from 'lucide-react';
import { useLiveCollection } from '../../hooks/useLiveCollection.js';
import { supabase } from '../../supabase/client.js';
import { getPublicUrl, uploadFile } from '../../supabase/storage.js';

const EMPTY = { name:'', description:'', price:'', image_url:'', stock:'100', is_active:true, file:null };
const safeName=(value)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export default function ProductIndex() {
  const products = useLiveCollection('products',{ order:{ column:'created_at', ascending:false } });
  const [form,setForm] = useState(EMPTY); const [editing,setEditing] = useState(null); const [open,setOpen] = useState(false); const [saving,setSaving] = useState(false); const [error,setError] = useState('');
  const showForm = (product=null) => { setEditing(product?.id || null); setForm(product ? { name:product.name || '', description:product.description || '', price:String(product.price || ''), image_url:product.image_url || product.image || '', stock:String(product.stock ?? 100), is_active:product.is_active !== false, file:null } : EMPTY); setOpen(true); setError(''); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { let imageUrl=form.image_url.trim()||null;if(form.file){const extension=form.file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`catalog/${safeName(form.name)}-${Date.now()}.${extension}`;await uploadFile('product-images',path,form.file);imageUrl=getPublicUrl('product-images',path);}const payload={ name:form.name.trim(), slug:safeName(form.name), description:form.description.trim() || null, price:Number(form.price), image_url:imageUrl, stock:Number(form.stock), is_active:form.is_active }; const query=editing ? supabase.from('products').update(payload).eq('id',editing) : supabase.from('products').insert(payload); const {error:saveError}=await query;if(saveError)throw saveError;setOpen(false); } catch(reason){setError(reason.message);} finally{setSaving(false);} };
  const remove = async (product) => { if(!confirm(`Hapus produk ${product.name}?`))return; const {error:deleteError}=await supabase.from('products').delete().eq('id',product.id); if(deleteError)setError(deleteError.message); };
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-xl font-bold text-gray-800">Produk</h1><p className="text-xs text-gray-400">Kelola katalog yang tampil di aplikasi.</p></div><button onClick={()=>showForm()} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white"><Plus size={15}/> Tambah Produk</button></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}<div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{products===null?<Loader2 className="animate-spin text-primary"/>:products.map((product)=><article key={product.id} className="overflow-hidden rounded-2xl border border-gray-100 bg-white p-2.5"><div className="aspect-square overflow-hidden rounded-xl bg-gray-100">{product.image_url&&<img src={product.image_url} alt={product.name} className="h-full w-full object-cover"/>}</div><h2 className="mt-2 line-clamp-1 text-sm font-bold">{product.name}</h2><p className="text-xs font-bold text-primary">Rp{Number(product.price).toLocaleString('id-ID')}</p><div className="mt-2 flex items-center justify-between"><span className={`rounded-full px-2 py-1 text-[9px] ${product.is_active?'bg-emerald-50 text-emerald-600':'bg-gray-100 text-gray-500'}`}>{product.is_active?'Aktif':'Nonaktif'} · Stok {product.stock}</span><span className="flex gap-1"><button onClick={()=>showForm(product)} className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-blue-600"><Edit2 size={13}/></button><button onClick={()=>remove(product)} className="grid h-8 w-8 place-items-center rounded-lg bg-red-50 text-red-600"><Trash2 size={13}/></button></span></div></article>)}</div>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={save} className="max-h-[90dvh] w-full max-w-lg space-y-3 overflow-y-auto rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{editing?'Edit':'Tambah'} Produk</h2><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="Nama produk" className="w-full rounded-xl border p-3 text-sm"/><textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} placeholder="Deskripsi" className="w-full rounded-xl border p-3 text-sm"/><div className="grid grid-cols-2 gap-3"><input required min="0" type="number" value={form.price} onChange={(e)=>setForm({...form,price:e.target.value})} placeholder="Harga" className="rounded-xl border p-3 text-sm"/><input required min="0" type="number" value={form.stock} onChange={(e)=>setForm({...form,stock:e.target.value})} placeholder="Stok" className="rounded-xl border p-3 text-sm"/></div><label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed text-xs text-gray-500"><ImagePlus className="mb-2 text-primary"/><span>{form.file?.name||'Upload gambar JPG, PNG, atau WebP'}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e)=>setForm({...form,file:e.target.files?.[0]||null})}/></label><input value={form.image_url} onChange={(e)=>setForm({...form,image_url:e.target.value})} placeholder="Atau URL gambar" className="w-full rounded-xl border p-3 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.is_active} onChange={(e)=>setForm({...form,is_active:e.target.checked})}/> Produk aktif</label><button disabled={saving} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary text-sm font-bold text-white">{saving&&<Loader2 size={15} className="animate-spin"/>} Simpan Produk</button></form></div>}
  </div>;
}
