import { Edit2, ExternalLink, MapPin, Navigation, Plus, Trash2 } from 'lucide-react';
import { CheckoutLocationMap } from './CheckoutLocationMap.jsx';

export function AddressSection({ addresses, selectedAddress, currentCoords, onSelect, onAdd, onEdit, onDelete, onOpenLocation }) {
  const mapCoords = currentCoords || (selectedAddress?.latitude && selectedAddress?.longitude ? { lat:Number(selectedAddress.latitude), lng:Number(selectedAddress.longitude), accuracy:15 } : null);
  return <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-card sm:p-5">
    <div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-bold text-dark">2. Alamat Pengiriman</h2><span className="rounded-full bg-gray-100 px-2 py-1 text-[9px] text-gray-500">{addresses.length} alamat</span></div>
    <div className="space-y-2.5">{addresses.map((address) => {
      const active = selectedAddress?.id === address.id;
      return <button type="button" key={address.id} onClick={() => onSelect(address.id)} className={`w-full rounded-xl border p-3.5 text-left ${active ? 'border-primary bg-primary-50' : 'border-gray-100 bg-gray-50'}`}><span className="flex items-start gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border-2 ${active ? 'border-primary' : 'border-gray-300'}`}>{active && <span className="h-2.5 w-2.5 rounded-full bg-primary"/>}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap gap-2"><strong className="text-xs text-dark">{address.label || 'Alamat'}</strong>{address.is_primary && <span className="rounded bg-primary px-2 py-0.5 text-[8px] font-bold text-white">Utama</span>}</span><span className="mt-1 block text-[10px] font-semibold text-gray-600">{address.recipient_name || 'Penerima'}{address.phone_number ? ` · ${address.phone_number}` : ''}</span><span className="mt-1 block text-[11px] leading-relaxed text-gray-500">{[address.full_address,address.city,address.postal_code].filter(Boolean).join(', ')}</span>{address.landmark && <span className="mt-1 block text-[9px] italic text-gray-400">Patokan: {address.landmark}</span>}</span><span className="flex gap-2 text-gray-400"><Edit2 onClick={(event) => { event.stopPropagation(); onEdit(address); }} size={14}/><Trash2 onClick={(event) => { event.stopPropagation(); onDelete(address); }} size={14} className="hover:text-red-500"/></span></span></button>;
    })}</div>
    {!addresses.length && <div className="rounded-xl border border-dashed border-gray-200 bg-gray-50 p-5 text-center"><MapPin className="mx-auto text-gray-300"/><p className="mt-2 text-xs text-gray-500">Belum ada alamat tersimpan</p></div>}
    <div className="mt-3 grid grid-cols-1 gap-2 xs:grid-cols-2"><button type="button" onClick={onAdd} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-dashed border-gray-200 text-xs font-semibold text-gray-600"><Plus size={14}/> Tambah Alamat</button><button type="button" onClick={onOpenLocation} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary-50 text-xs font-semibold text-primary"><Navigation size={14}/> Gunakan Lokasi Saat Ini</button></div>
    <div className="mt-4"><span className="mb-2 block text-[10px] font-semibold text-gray-500">Lokasi di peta</span><CheckoutLocationMap coords={mapCoords} className="h-40"/>{mapCoords && <a href={`https://www.google.com/maps?q=${mapCoords.lat},${mapCoords.lng}`} target="_blank" rel="noreferrer" className="mt-2 flex min-h-9 items-center justify-center gap-1 rounded-xl bg-gray-50 text-[9px] font-semibold text-gray-500"><ExternalLink size={11}/> Buka Google Maps</a>}</div>
  </section>;
}
