import { useEffect, useState } from 'react';
import { Check, Edit2, Loader2, X } from 'lucide-react';

export function ReceiverSection({ profile, onSave, saving = false }) {
  const [editing,setEditing] = useState(false);
  const [draft,setDraft] = useState({ fullName:'', phone:'' });
  useEffect(() => setDraft({ fullName:profile?.full_name || '', phone:profile?.phone || '' }),[profile?.full_name,profile?.phone]);
  const submit = async (event) => { event.preventDefault(); await onSave(draft); setEditing(false); };
  return <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-card sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-bold text-dark">1. Data Penerima</h2><button type="button" onClick={() => setEditing((value) => !value)} className="inline-flex items-center gap-1 rounded-lg bg-primary-50 px-2.5 py-1.5 text-[10px] font-semibold text-primary"><Edit2 size={13}/> {editing ? 'Batal' : 'Edit'}</button></div>{editing ? <form onSubmit={submit} className="space-y-3"><label className="block text-[10px] font-semibold text-gray-500">Nama lengkap<input required value={draft.fullName} onChange={(e) => setDraft({...draft,fullName:e.target.value})} className="mt-1 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-3 text-sm outline-none focus:border-primary focus:bg-white"/></label><label className="block text-[10px] font-semibold text-gray-500">Nomor WhatsApp<input required inputMode="tel" value={draft.phone} onChange={(e) => setDraft({...draft,phone:e.target.value})} className="mt-1 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-3 text-sm outline-none focus:border-primary focus:bg-white"/></label><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setEditing(false)} className="flex min-h-10 items-center justify-center gap-1 rounded-xl border border-gray-200 text-xs text-gray-500"><X size={13}/> Batal</button><button disabled={saving} className="flex min-h-10 items-center justify-center gap-1 rounded-xl bg-primary text-xs font-bold text-white disabled:opacity-60">{saving ? <Loader2 size={13} className="animate-spin"/> : <Check size={13}/>} Simpan</button></div></form> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="rounded-xl border border-gray-100 bg-gray-50 p-3"><span className="block text-[9px] uppercase tracking-wide text-gray-400">Nama Lengkap</span><strong className="mt-1 block text-xs text-gray-700">{profile?.full_name || 'Belum diisi'}</strong></div><div className="rounded-xl border border-gray-100 bg-gray-50 p-3"><span className="block text-[9px] uppercase tracking-wide text-gray-400">No. WhatsApp</span><strong className="mt-1 block text-xs text-gray-700">{profile?.phone || 'Belum diisi'}</strong></div><div className="rounded-xl border border-gray-100 bg-gray-50 p-3 sm:col-span-2"><span className="block text-[9px] uppercase tracking-wide text-gray-400">Email</span><strong className="mt-1 block break-all text-xs text-gray-700">{profile?.email || 'Belum diisi'}</strong></div></div>}</section>;
}
