export const TABLES = {
  PROFILES: "profiles",
  PRODUCTS: "products",
  FLASH_SALES: "flash_sales",
  CATEGORIES: "categories",
  ORDERS: "orders",
  ORDER_ITEMS: "order_items",
  ORDER_DETAIL: "order_detail",
  MEMBER_POINT: "member_point",
  REWARDS: "rewards",
  REVIEWS: "reviews",
  NOTIFICATIONS: "notifications",
  ACTIVITY_LOGS: "activity_logs",
  MAINTENANCE: "maintenance",
  STORES: "stores",
  PROMOS: "promos",
  ADMIN_USERS: "admin_users",
  ADMIN_SESSIONS: "admin_sessions",
  WISHLIST: "wishlist",
  APK_VERSIONS: "apk_versions",
  STORE_SETTINGS: "store_settings",
  APP_CONFIG: "app_config",
};

export const BUCKETS = {
  PRODUCT_IMAGES: "product-images",
  BANNERS: "banners",
  APK: "apk",
  CATEGORY_IMAGES: "category-images",
};
