import { Clock3, Globe2, Laptop, Loader2, MapPin, Monitor, RefreshCw, Smartphone, Tablet, Wifi } from "lucide-react";
import { useAdminDeviceSessions } from "../../hooks/useAdminDeviceSessions.js";

const format = (value) => value ? new Date(value).toLocaleString("id-ID", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "Belum tersedia";
const iconFor = (type) => type === "mobile" ? Smartphone : type === "tablet" ? Tablet : Monitor;

export default function AdminDeviceSessions({ adminId }) {
  const { sessions, loading, deviceId } = useAdminDeviceSessions(adminId);
  return <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Laptop size={20}/></span><div><h2 className="font-bold text-gray-900">Sesi & Perangkat Admin</h2><p className="mt-0.5 text-xs text-gray-500">Perangkat yang menggunakan akun ini, diperbarui realtime.</p></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-600"><Wifi size={13}/>{sessions.filter((item) => !item.ended_at && Date.now() - new Date(item.last_seen_at).getTime() < 300_000).length} SESI AKTIF</span></div>
    {loading ? <div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-blue-500"/></div> : sessions.length ? <div className="mt-5 grid gap-3 lg:grid-cols-2">{sessions.map((session) => { const Icon = iconFor(session.device_type); const current = session.device_id === deviceId; const online = !session.ended_at && Date.now() - new Date(session.last_seen_at).getTime() < 300_000; return <article key={session.id || session.device_id} className={`rounded-2xl border p-4 ${current ? "border-blue-200 bg-blue-50/40" : "border-gray-100 bg-gray-50/50"}`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${current ? "bg-blue-600 text-white" : "bg-white text-gray-500"}`}><Icon size={20}/></span><div className="min-w-0"><h3 className="truncate text-sm font-bold text-gray-800">{session.device_name || "Perangkat admin"}</h3><p className="mt-1 text-[10px] text-gray-400">{session.screen_size || "Ukuran layar tidak diketahui"}</p></div></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${online ? "bg-emerald-100 text-emerald-700" : "bg-gray-200 text-gray-500"}`}>{current ? "PERANGKAT INI" : online ? "ONLINE" : "TIDAK AKTIF"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><Info icon={Globe2} label="Browser" value={session.browser}/><Info icon={Monitor} label="Sistem" value={session.operating_system}/><Info icon={MapPin} label="Wilayah / zona" value={session.timezone}/><Info icon={Clock3} label="Aktivitas terakhir" value={format(session.last_seen_at)}/></div></article>})}</div> : <div className="mt-5 rounded-2xl border border-dashed border-gray-200 bg-gray-50 p-8 text-center"><RefreshCw className="mx-auto text-gray-300"/><p className="mt-3 text-sm font-bold text-gray-600">Data sesi belum tersedia</p><p className="mt-1 text-xs text-gray-400">Jalankan SQL sesi perangkat, lalu buka kembali halaman ini.</p></div>}
    <p className="mt-4 text-[10px] leading-5 text-gray-400">Wilayah diperkirakan dari zona waktu perangkat. Token login, kata sandi, dan lokasi GPS tidak pernah disimpan.</p>
  </section>;
}
function Info({ icon: Icon, label, value }) { return <div className="min-w-0 rounded-xl bg-white p-3"><span className="flex items-center gap-1.5 text-gray-400"><Icon size={12}/>{label}</span><strong className="mt-1 block truncate text-gray-700">{value || "Tidak diketahui"}</strong></div>; }
