import { useCallback, useEffect, useState } from "react";
import { Building2, Loader2, Pencil, Plus, QrCode, RefreshCw, Save, Smartphone, Trash2, WalletCards, X } from "lucide-react";
import Modal from "../../components/ui/Modal.jsx";
import { listMerchantAccounts, removeMerchantAccount, saveMerchantAccount } from "../../services/merchantAccountService.js";

const EMPTY = { id: null, account_type: "bank", method_code: "transfer", provider_name: "", account_name: "", account_number: "", qr_image_url: "", instructions: "", is_active: true, is_primary: false, sort_order: 0 };
const input = "mt-1.5 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-100";
const labels = { bank: "Rekening Bank", ewallet: "Dompet Digital", qris: "QRIS", cod: "Bayar di Tempat" };
const icons = { bank: Building2, ewallet: Smartphone, qris: QrCode, cod: WalletCards };

export default function MerchantAccountsPage() {
  const [rows, setRows] = useState(null);
  const [form, setForm] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setError(""); try { setRows(await listMerchantAccounts()); } catch (reason) { setRows([]); setError(reason.message || "Rekening toko gagal dimuat."); } }, []);
  useEffect(() => { load(); }, [load]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await saveMerchantAccount(form); setForm(null); setNotice("Rekening toko berhasil disimpan dan tersinkron ke web serta APK."); await load(); } catch (reason) { setError(reason.message || "Rekening tidak dapat disimpan."); } finally { setSaving(false); } };
  const remove = async () => { setSaving(true); try { await removeMerchantAccount(deleting.id); setDeleting(null); setNotice("Rekening toko berhasil dihapus."); await load(); } catch (reason) { setError(reason.message || "Rekening tidak dapat dihapus."); setDeleting(null); } finally { setSaving(false); } };

  return <div className="space-y-5">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold"><WalletCards className="text-orange-500"/>Rekening Toko</h1><p className="mt-1 text-sm text-gray-500">Kelola rekening pembayaran yang tampil di website dan aplikasi Android.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex min-h-10 items-center gap-2 rounded-xl border bg-white px-4 text-xs font-bold"><RefreshCw size={14}/>Muat Ulang</button><button onClick={()=>setForm({...EMPTY})} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-orange-500 px-4 text-xs font-bold text-white"><Plus size={15}/>Tambah Rekening</button></div></header>
    {error&&<p role="alert" className="rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    {rows===null?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-orange-500"/></div>:rows.length?<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map((row)=>{const Icon=icons[row.account_type]||WalletCards;return <article key={row.id} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-orange-50 text-orange-600"><Icon size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${row.is_active?"bg-emerald-50 text-emerald-700":"bg-gray-100 text-gray-500"}`}>{row.is_active?"AKTIF":"NONAKTIF"}</span>{row.is_primary&&<span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">UTAMA</span>}</div><h2 className="mt-2 truncate text-sm font-bold">{row.provider_name}</h2><p className="text-[10px] text-gray-400">{labels[row.account_type]} · {row.method_code}</p></div></div><dl className="mt-4 space-y-2 rounded-xl bg-gray-50 p-3 text-xs"><div><dt className="text-[9px] uppercase text-gray-400">Tujuan</dt><dd className="mt-0.5 break-all font-bold">{row.account_number||row.qr_image_url||"Pembayaran saat diterima"}</dd></div><div><dt className="text-[9px] uppercase text-gray-400">Atas nama</dt><dd className="mt-0.5 font-semibold">{row.account_name||"-"}</dd></div></dl><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setForm({...row})} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-blue-50 text-xs font-bold text-blue-700"><Pencil size={14}/>Ubah</button><button onClick={()=>setDeleting(row)} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-red-50 text-xs font-bold text-red-700"><Trash2 size={14}/>Hapus</button></div></article>})}</section>:<section className="rounded-2xl border border-dashed bg-white p-12 text-center"><WalletCards className="mx-auto text-gray-300" size={38}/><h2 className="mt-3 text-sm font-bold">Belum ada rekening toko</h2><p className="mt-1 text-xs text-gray-400">Tambahkan rekening pertama tanpa membuat data contoh palsu.</p></section>}
    <Modal open={Boolean(form)} title={form?.id?"Ubah Rekening Toko":"Tambah Rekening Toko"} onClose={()=>!saving&&setForm(null)}>{form&&<form onSubmit={submit} className="space-y-3"><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Jenis<select value={form.account_type} onChange={(e)=>set("account_type",e.target.value)} className={input}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-bold">Kode Metode<input required value={form.method_code} onChange={(e)=>set("method_code",e.target.value.toLowerCase())} placeholder="transfer" className={input}/></label></div><label className="block text-xs font-bold">Bank / Provider<input required value={form.provider_name} onChange={(e)=>set("provider_name",e.target.value)} placeholder="BCA, DANA, QRIS" className={input}/></label>{["bank","ewallet"].includes(form.account_type)&&<label className="block text-xs font-bold">Nomor Rekening / Akun<input required inputMode="numeric" value={form.account_number||""} onChange={(e)=>set("account_number",e.target.value.replace(/\D/g,""))} className={input}/></label>}{form.account_type==="qris"&&<label className="block text-xs font-bold">URL Gambar QRIS (HTTPS)<input required type="url" value={form.qr_image_url||""} onChange={(e)=>set("qr_image_url",e.target.value)} className={input}/></label>}<label className="block text-xs font-bold">Nama Pemilik<input value={form.account_name||""} onChange={(e)=>set("account_name",e.target.value)} className={input}/></label><label className="block text-xs font-bold">Instruksi<textarea rows="3" value={form.instructions||""} onChange={(e)=>set("instructions",e.target.value)} className={`${input} py-3`}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Urutan<input min="0" type="number" value={form.sort_order} onChange={(e)=>set("sort_order",e.target.value)} className={input}/></label><div className="space-y-3 pt-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_active} onChange={(e)=>set("is_active",e.target.checked)} className="accent-orange-500"/>Aktif di pelanggan</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_primary} onChange={(e)=>set("is_primary",e.target.checked)} className="accent-orange-500"/>Rekening utama</label></div></div><div className="grid grid-cols-2 gap-2 pt-2"><button type="button" onClick={()=>setForm(null)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gray-100 text-sm font-bold"><X size={15}/>Batal</button><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-orange-500 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>}Simpan</button></div></form>}</Modal>
    <Modal open={Boolean(deleting)} title="Hapus rekening toko?" onClose={()=>!saving&&setDeleting(null)}><p className="text-sm text-gray-600">Rekening <strong>{deleting?.provider_name}</strong> akan langsung hilang dari pilihan pelanggan.</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setDeleting(null)} className="min-h-11 rounded-xl bg-gray-100 text-sm font-bold">Batal</button><button disabled={saving} onClick={remove} className="min-h-11 rounded-xl bg-red-600 text-sm font-bold text-white">Hapus</button></div></Modal>
  </div>;
}
