import { useState } from 'react';
import { Edit2, Loader2, Plus, Trash2, X, Zap } from 'lucide-react';
import { useLiveCollection } from '../../hooks/useLiveCollection.js';
import { supabase } from '../../supabase/client.js';

const datetime = (value) => value ? new Date(value).toISOString().slice(0,16) : '';
export default function FlashSaleIndex(){
  const sales=useLiveCollection('flash_sales',{ select:'*, products(id,name,image_url,price)', order:{column:'ends_at'} }); const products=useLiveCollection('products',{filters:{is_active:true},order:{column:'name'}}); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [form,setForm]=useState({product_id:'',sale_price:'',original_price:'',flash_stock:'10',starts_at:datetime(new Date()),ends_at:datetime(Date.now()+86400000),is_active:true});
  const show=(sale=null)=>{setEditing(sale?.id||null);setForm(sale?{product_id:sale.product_id,sale_price:sale.sale_price,original_price:sale.original_price,flash_stock:sale.flash_stock,starts_at:datetime(sale.starts_at),ends_at:datetime(sale.ends_at),is_active:sale.is_active}:{product_id:'',sale_price:'',original_price:'',flash_stock:'10',starts_at:datetime(new Date()),ends_at:datetime(Date.now()+86400000),is_active:true});setOpen(true);setError('');};
  const save=async(e)=>{e.preventDefault();setSaving(true);const payload={...form,sale_price:Number(form.sale_price),original_price:Number(form.original_price),flash_stock:Number(form.flash_stock),starts_at:new Date(form.starts_at).toISOString(),ends_at:new Date(form.ends_at).toISOString()};const query=editing?supabase.from('flash_sales').update(payload).eq('id',editing):supabase.from('flash_sales').insert(payload);const {error:err}=await query;setSaving(false);if(err)setError(err.message);else setOpen(false);};
  const remove=async(id)=>{if(confirm('Hapus Flash Sale ini?')){const {error:err}=await supabase.from('flash_sales').delete().eq('id',id);if(err)setError(err.message);}};
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Zap className="text-amber-500"/> Flash Sale</h1><p className="text-xs text-gray-400">Atur harga, stok promo, dan jadwal tampil.</p></div><button onClick={()=>show()} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white"><Plus size={15}/> Tambah</button></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}<div className="space-y-2">{sales===null?<Loader2 className="animate-spin"/>:sales.map(sale=><article key={sale.id} className="flex items-center gap-3 rounded-2xl border bg-white p-3"><img src={sale.products?.image_url} className="h-14 w-14 rounded-xl bg-gray-100 object-cover"/><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{sale.products?.name}</strong><span className="text-xs text-red-600">Rp{Number(sale.sale_price).toLocaleString('id-ID')} · Stok {sale.flash_stock}</span><p className="text-[9px] text-gray-400">Sampai {new Date(sale.ends_at).toLocaleString('id-ID')}</p></div><button onClick={()=>show(sale)} className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><Edit2 size={14}/></button><button onClick={()=>remove(sale.id)} className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-600"><Trash2 size={14}/></button></article>)}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-3xl bg-white p-5"><div className="flex justify-between"><strong>{editing?'Edit':'Tambah'} Flash Sale</strong><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><select required value={form.product_id} onChange={e=>{const p=products?.find(x=>x.id===e.target.value);setForm({...form,product_id:e.target.value,original_price:p?.price||form.original_price});}} className="w-full rounded-xl border p-3 text-sm"><option value="">Pilih produk</option>{products?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input required type="number" min="0" value={form.original_price} onChange={e=>setForm({...form,original_price:e.target.value})} placeholder="Harga normal" className="rounded-xl border p-3 text-sm"/><input required type="number" min="0" value={form.sale_price} onChange={e=>setForm({...form,sale_price:e.target.value})} placeholder="Harga promo" className="rounded-xl border p-3 text-sm"/></div><input required type="number" min="1" value={form.flash_stock} onChange={e=>setForm({...form,flash_stock:e.target.value})} placeholder="Stok Flash Sale" className="w-full rounded-xl border p-3 text-sm"/><div className="grid grid-cols-2 gap-2"><input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})} className="rounded-xl border p-2 text-xs"/><input required type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})} className="rounded-xl border p-2 text-xs"/></div><label className="flex gap-2 text-xs"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Aktif</label><button disabled={saving} className="min-h-11 w-full rounded-xl bg-primary font-bold text-white">Simpan Flash Sale</button></form></div>}</div>;
}
