import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ExternalLink, MapPin, MessageCircle, RotateCcw, ShieldCheck, Smartphone, Store, Wifi, WifiOff } from "lucide-react";
import StoreControlCard from "../../components/dashboard/StoreControlCard.jsx";
import { useDashboardStats } from "../../hooks/useDashboardStats.js";
import { updateStoreInfo } from "../../services/dashboardService.js";
import GoogleMapsLogo from "../../components/ui/GoogleMapsLogo.jsx";

const Navigation=GoogleMapsLogo;

const comparable = (value = {}) => JSON.stringify({ name:value.name||"", address:value.address||"", phone:value.phone||"", latitude:Number(value.latitude), longitude:Number(value.longitude), open_time:value.open_time?.slice?.(0,5)||"", close_time:value.close_time?.slice?.(0,5)||"", is_open:value.is_open!==false });

export default function StoreIndex() {
  const data=useDashboardStats();
  const [store,setStore]=useState({});
  const [baseline,setBaseline]=useState({});
  const [saving,setSaving]=useState(false);
  const [notice,setNotice]=useState(null);
  const dirty=comparable(store)!==comparable(baseline);
  useEffect(()=>{if(data.storeInfo&&!dirty){setStore(data.storeInfo);setBaseline(data.storeInfo);}},[data.storeInfo]); // eslint-disable-line react-hooks/exhaustive-deps

  const latitude=Number(store.latitude),longitude=Number(store.longitude);
  const validCoordinates=Number.isFinite(latitude)&&latitude>=-90&&latitude<=90&&Number.isFinite(longitude)&&longitude>=-180&&longitude<=180;
  const validPhone=/^\+?\d{8,16}$/.test(String(store.phone||"").replace(/\s/g,""));
  const checks=useMemo(()=>[["Nama outlet",Boolean(store.name?.trim()),"Identitas yang dilihat pelanggan"],["Alamat lengkap",Boolean(store.address?.trim()&&store.address.trim().length>=10),"Alamat tujuan pelanggan dan kurir"],["WhatsApp",validPhone,"Nomor aktif dengan kode negara"],["Koordinat peta",validCoordinates,"Latitude dan longitude outlet"],["Jam operasional",Boolean(store.open_time&&store.close_time),"Waktu layanan pesanan"]],[store,validPhone,validCoordinates]);
  const completeness=Math.round(checks.filter((item)=>item[1]).length/checks.length*100);
  const connected=data.realtimeStatus==="SUBSCRIBED";
  const mapUrl=validCoordinates?`https://www.google.com/maps?q=${latitude},${longitude}`:null;
  const whatsappUrl=validPhone?`https://wa.me/${String(store.phone).replace(/\D/g,"")}`:null;

  const save=async(next=store)=>{setSaving(true);setNotice(null);try{const saved=await updateStoreInfo(next);const normalized={...next,...saved};setStore(normalized);setBaseline(normalized);setNotice({type:"success",text:"Lokasi toko berhasil disimpan ke Supabase dan disinkronkan ke Web serta APK."});}catch(reason){setNotice({type:"error",text:reason.message||"Lokasi toko gagal disimpan."});}finally{setSaving(false);}};
  const toggle=(is_open)=>{const next={...store,is_open};setStore(next);save(next);};
  const reset=()=>{setStore(baseline);setNotice({type:"success",text:"Perubahan yang belum disimpan berhasil dibatalkan."});};

  return <div className="space-y-5">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-gray-950 via-gray-900 to-orange-950 p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-orange-300"><Store size={14}/>Store Location Control Center</p><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">Lokasi & Informasi Toko</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-white/60 sm:text-sm">Kelola identitas outlet, alamat, kontak, titik peta, jam layanan, dan status penerimaan pesanan dari satu sumber Supabase.</p></div><div className="flex flex-wrap gap-2"><span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-[10px] font-bold ${connected?"bg-emerald-400/15 text-emerald-300":"bg-amber-400/15 text-amber-300"}`}>{connected?<Wifi size={13}/>:<WifiOff size={13}/>} {connected?"REALTIME TERHUBUNG":"MENGHUBUNGKAN"}</span><span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-[10px] font-bold ${store.is_open!==false?"bg-emerald-400/15 text-emerald-300":"bg-red-400/15 text-red-300"}`}><span className={`h-2 w-2 rounded-full ${store.is_open!==false?"animate-pulse bg-emerald-400":"bg-red-400"}`}/>{store.is_open!==false?"TOKO BUKA":"TOKO TUTUP"}</span></div></div></header>
    {(data.error||notice)&&<p role="alert" className={`flex items-start gap-2 rounded-xl border p-3 text-xs ${(data.error||notice?.type==="error")?"border-red-200 bg-red-50 text-red-600":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{(data.error||notice?.type==="error")?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>} {data.error||notice?.text}</p>}
    {dirty&&<div className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs font-semibold text-amber-800"><AlertTriangle size={15}/>Ada perubahan informasi yang belum disimpan.</p><button onClick={reset} disabled={saving} className="inline-flex min-h-9 items-center justify-center gap-2 rounded-xl bg-white px-3 text-[10px] font-bold text-amber-700 shadow-sm"><RotateCcw size={13}/>Batalkan Perubahan</button></div>}
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric Icon={ShieldCheck} label="Kelengkapan Informasi" value={`${completeness}%`} color="bg-orange-50 text-primary" progress={completeness}/><Metric Icon={MapPin} label="Koordinat Outlet" value={validCoordinates?`${latitude.toFixed(5)}, ${longitude.toFixed(5)}`:"Belum valid"} color="bg-blue-50 text-blue-600"/><Metric Icon={Clock3} label="Jam Pelayanan" value={`${store.open_time?.slice?.(0,5)||"--:--"} – ${store.close_time?.slice?.(0,5)||"--:--"}`} color="bg-emerald-50 text-emerald-600"/><Metric Icon={Smartphone} label="Dashboard · Web · APK" value="3 Kanal Aktif" color="bg-violet-50 text-violet-600"/></div>
    <div className="grid gap-4 2xl:grid-cols-[1fr_330px]"><StoreControlCard store={store} saving={saving} onChange={setStore} onSave={()=>save()} onToggle={toggle}/><aside className="space-y-4"><section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">Pemeriksaan Konfigurasi</h2><p className="mt-1 text-[10px] text-gray-400">Validasi sebelum informasi dipublikasikan.</p><div className="mt-3 space-y-2">{checks.map(([label,complete,description])=><div key={label} className="flex gap-2.5 rounded-xl bg-gray-50 p-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${complete?"bg-emerald-100 text-emerald-600":"bg-amber-100 text-amber-600"}`}>{complete?<CheckCircle2 size={12}/>:<AlertTriangle size={11}/>}</span><div><strong className="block text-[10px] text-gray-700">{label}</strong><p className="mt-0.5 text-[9px] leading-4 text-gray-400">{description}</p></div></div>)}</div></section><section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">Akses Cepat</h2><div className="mt-3 grid gap-2">{mapUrl&&<a href={mapUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-between rounded-xl bg-blue-50 px-3 text-xs font-bold text-blue-600"><span className="flex items-center gap-2"><Navigation size={14}/>Periksa Google Maps</span><ExternalLink size={13}/></a>}{whatsappUrl&&<a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-between rounded-xl bg-emerald-50 px-3 text-xs font-bold text-emerald-600"><span className="flex items-center gap-2"><MessageCircle size={14}/>Uji WhatsApp Toko</span><ExternalLink size={13}/></a>}</div></section><section className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><h3 className="text-xs font-bold text-blue-800">Dampak Perubahan</h3><ul className="mt-2 space-y-2 text-[10px] leading-4 text-blue-700"><li>• Nama dan alamat tampil pada informasi outlet.</li><li>• Koordinat mengarahkan pelanggan ke lokasi toko.</li><li>• WhatsApp digunakan untuk kontak bantuan.</li><li>• Status tutup menghentikan pesanan baru.</li><li>• Web dan APK menerima perubahan realtime.</li></ul></section></aside></div>
    <footer className="flex flex-col gap-2 rounded-2xl border border-gray-100 bg-white p-4 text-[10px] text-gray-500 sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-emerald-600"/>Data dilindungi validasi admin dan Supabase Row Level Security.</span><span>{data.lastUpdated?`Sinkronisasi terakhir ${data.lastUpdated.toLocaleString("id-ID")}`:"Menunggu data realtime"}</span></footer>
  </div>;
}

function Metric({Icon,label,value,color,progress}) { return <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><span className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}><Icon size={17}/></span><strong className="mt-3 block truncate text-base">{value}</strong><p className="mt-1 text-[10px] text-gray-500">{label}</p>{progress!==undefined&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-primary" style={{width:`${progress}%`}}/></div>}</div>; }
