import { useEffect, useState } from "react";
import { Clock } from "lucide-react";
import { useDashboardStats } from "../../hooks/useDashboardStats.js";
import { updateStoreInfo } from "../../services/dashboardService.js";

export default function OperatingHours() {
  const data = useDashboardStats(); const [store,setStore]=useState({}); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>setStore(data.storeInfo||{}),[data.storeInfo]);
  const save=async(event)=>{event.preventDefault();setSaving(true);setMessage("");try{await updateStoreInfo(store);setMessage("Jam operasional berhasil disinkronkan ke Web dan APK.");}catch(error){setMessage(error.message);}finally{setSaving(false);}};
  return <div className="max-w-xl space-y-4"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Clock className="text-primary"/>Jam Operasional</h1><p className="text-sm text-gray-500">Saat toko ditutup, aplikasi pelanggan tidak menerima pesanan baru.</p></div>{message&&<p className="rounded-xl border bg-white p-3 text-sm">{message}</p>}<form onSubmit={save} className="space-y-5 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><strong className="text-sm">Status toko sekarang</strong><p className="text-xs text-gray-500">{store.is_open!==false?"Buka dan menerima pesanan":"Tutup sementara"}</p></div><button type="button" role="switch" aria-checked={store.is_open!==false} onClick={()=>setStore({...store,is_open:store.is_open===false})} className={`rounded-full px-4 py-2 text-xs font-bold ${store.is_open!==false?'bg-green-50 text-green-600':'bg-gray-100 text-gray-500'}`}>{store.is_open!==false?'BUKA':'TUTUP'}</button></div><div className="grid grid-cols-2 gap-3"><label className="text-xs text-gray-500">Jam buka<input required type="time" value={store.open_time?.slice?.(0,5)||"08:00"} onChange={e=>setStore({...store,open_time:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs text-gray-500">Jam tutup<input required type="time" value={store.close_time?.slice?.(0,5)||"21:00"} onChange={e=>setStore({...store,close_time:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label></div><button disabled={saving} className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Menyimpan...":"Simpan Jam Operasional"}</button></form></div>;
}
